name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [self-hosted]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test:unit --ci --coverage

      - name: Set COMPOSE_PROJECT_NAME for voconed
        run: echo COMPOSE_PROJECT_NAME=${RANDOM}${RANDOM}_ci >> $GITHUB_ENV

      - name: Start voconed (ephemeral vochain for integration test)
        run: |
          docker-compose -f test/integration/docker-compose.yml up -d
          echo -n "voconed_hostport=" >> $GITHUB_ENV
          docker-compose -f test/integration/docker-compose.yml port voconed 9095 >> $GITHUB_ENV

      - name: Integration tests
        run: npm run test test/integration --ci --coverage --maxWorkers=2
        env:
          API_URL: http://${{ env.voconed_hostport }}/dvote
          FAUCET_URL: ${{ secrets.FAUCET_URL }}
          FAUCET_AUTH_TOKEN: ${{ secrets.FAUCET_AUTH_TOKEN }}
          FAUCET_TOKEN_LIMIT: 100

      - name: Stop voconed (ephemeral vochain for integration test)
        if: success() || failure()
        run: |
          docker-compose -f test/integration/docker-compose.yml down -v
